version: '3'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src

  server:
    build: ./server
    ports:
      - 3001:3001
    volumes:
      - ./server:/app/server